# Generated by Django 4.2.4 on 2023-08-31 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.IntegerField(choices=[(1, 'Documents'), (2, 'Video'), (3, 'Audio'), (4, 'Link')])),
                ('documents', models.FileField(upload_to='order_documents/')),
                ('deadline', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('industries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translate.industry')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translate.service')),
                ('source_language', models.ManyToManyField(related_name='source_orders', to='translate.language')),
                ('target_language', models.ManyToManyField(related_name='target_orders', to='translate.language')),
            ],
        ),
    ]
