# Generated by Django 4.2.4 on 2023-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='order_documents/'),
        ),
    ]
